[package]
name = "macro_orm"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
name = "macro_orm"
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = {version="2.0.114",features=["full"]}
